// Copyright (c) 2026 Jasper Sinclair
// SPDX-License-Identifier: GPL-3.0-only

#include <cstddef>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <iterator>
#include <vector>

int main(const int argc, char* argv[]){
  if (argc != 3){
    std::cerr << "Usage: embed_file <input> <output>\n";
    return 1;
  }

  std::ifstream input(argv[1],std::ios::binary);
  if (!input){
    std::cerr << "Cannot open input file: " << argv[1] << '\n';
    return 1;
  }

  const std::vector<unsigned char> data{
    std::istreambuf_iterator<char>{input},
    std::istreambuf_iterator<char>{}
  };

  if (input.bad()){
    std::cerr << "Cannot read input file: " << argv[1] << '\n';
    return 1;
  }

  std::ofstream output(argv[2],std::ios::trunc);
  if (!output){
    std::cerr << "Cannot create output file: " << argv[2] << '\n';
    return 1;
  }

  output <<
R"(// -----------------------------------------------------------------------------
// Generated by embed_file.cpp
// DO NOT EDIT
// -----------------------------------------------------------------------------

#include <cstddef>

extern const unsigned char g_default_net[];
extern const size_t g_default_net_size;

alignas(64) const unsigned char g_default_net[] = {
)";

  output << std::hex << std::setfill('0');

  for (std::size_t i = 0;i < data.size();++i){
    if (i % 16 == 0)
      output << "    ";

    output << "0x"
      << std::setw(2)
      << static_cast<unsigned>(data[i]);

    const bool last_byte = i + 1 == data.size();
    const bool line_end = i % 16 == 15 || last_byte;

    if (!last_byte)
      output << ',';

    if (line_end)
      output << '\n';
    else
      output << ' ';
  }

  output <<
R"(};

const size_t g_default_net_size = sizeof(g_default_net);
)";

  if (!output){
    std::cerr << "Cannot write output file: " << argv[2] << '\n';
    return 1;
  }

  std::cout << "Embedded "
    << data.size()
    << " bytes into "
    << argv[2]
    << '\n';
}
